name: Build webOS IPK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install CLI
        run: npm install -g @webosose/ares-cli
      - name: Package
        run: |
          # هذا السطر يبحث عن المجلد الصحيح الذي يحتوي الملفات
          TARGET_DIR=$(find . -name appinfo.json -printf '%h\n' | head -n 1)
          ares-package $TARGET_DIR
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Google-App-4K
          path: "**/*.ipk"
